project:
  type: manuscript
  output-dir: docs
  render:
    - index.qmd
    - appendices/*.qmd

toc: false

manuscript:
  article: index.qmd
  manuscript-url: https://br-johnson.github.io/sdm-paper/
  resources:
    - examples/Cal_DMP.pdf

format:
  apaquarto-docx: default
  html: default
  pdf: default

execute:
  freeze: true

editor: visual

